### ISSUE TITLE
Incremento da página de estrutura curricular

### ISSUE THREAD

**Issue by Peedrooo** [Peedrooo/Remaster_Sigaa_Web_Mobile#15]
## Motivação

Em entrevistas foram levantados informações a serem dispostas  na tela de estrutura curricular

## Critérios de aceitação

- [x] Disposição de IRA
- [x] Disposição de MP
- [x] Dispoisição de barra de progresso
- [x] Disposição de fluxo de obrigatoriedade em grade
- [x] Disposição de consulta semelhante a mw

## Tarefas

- [x] Criação de página contendo IRA, MP, barra de progresso, e dispoisição de consulta semelhante ao mw, além de botão para a visualização de fluxo

**Comment by LuizPettengill** [comment]
Consulta semelhante a mw Desconsiderada.
